name: zego_zimkit
description: zego imkit.
version: 0.0.1
homepage: https://www.zegocloud.com/
publish_to: 'none' 

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  zego_zim: ^2.5.0+1
  cached_network_image: ^3.2.3
  permission_handler: ^10.2.0
  wakelock: ^0.6.2
  http: ^0.13.5
  encrypt: ^5.0.1
  logging: ^1.1.0
  badges: ^2.0.3
  async: any
  file_picker: ^5.2.3
  flutter_screenutil: ^5.6.0
  #Google fonts
  google_fonts: ^3.0.1
  #choose image/video
  image_picker: ^0.8.6
  better_player:
    git:
      url: https://github.com/hoanghieu-savvycom/betterplayer.git
      ref: Issue1057
  youtube_player_flutter: ^8.1.1
  intl: ^0.18.0
  extended_image: ^6.1.0
  grouped_list: ^5.1.2
  # Toast
  fluttertoast: ^8.1.1
  #url
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: any
  flutter_lints: any
  import_sorter: any

import_sorter:
  comments: false

flutter:
  uses-material-design: true
  assets:
    # call
    - assets/
    - assets/icons/